name: budget_giornaliero
description: Un'applicazione per calcolare il budget giornaliero.
publish_to: "none"
version: 2.4.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  google_fonts: ^6.3.3
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  excel: ^4.0.3
  path_provider: ^2.1.0
  fl_chart: ^1.1.1
  file_picker: ^10.3.7
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  local_notifier: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.7

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

# Configurazione MSIX per Windows
msix_config:
  display_name: Budget Giornaliero
  publisher_display_name: Massimo Lo Sciuto
  identity_name: com.losciuto.budgetgiornaliero
  msix_version: 2.4.0.0
  logo_path: assets\icon.png
  capabilities: internetClient
  languages: it-IT, en-US
