import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'it': {
      'title': 'Budget Giornaliero',
      'subtitle': 'Gestione spese mensili',
      'target_date': 'Data Fine Budget',
      'total_budget': 'Importo Disponibile',
      'hint_budget': 'Inserisci il tuo budget totale',
      'today': 'Data di Oggi',
      'days_remaining': 'Giorni Mancanti',
      'daily_available': 'Puoi spendere al giorno:',
      'expired': 'Scaduto',
      'info': 'Informazioni',
      'add_expense': 'Aggiungi Spesa',
      'expenses': 'Spese Recenti',
      'no_expenses': 'Nessuna spesa registrata',
      'spent': 'Totale Speso',
      'remaining': 'Rimanente',
      'description': 'Descrizione',
      'amount': 'Importo',
      'cancel': 'Annulla',
      'add': 'Aggiungi',
      'notification_title': 'Budget Giornaliero',
      'notification_body': 'Hai ancora {amount} disponibili per oggi!',
      'settings': 'Impostazioni',
      'enable_notifications': 'Abilita Notifiche Giornaliere',
      'export_excel': 'Esporta in Excel',
      'export_success': 'File esportato con successo!',
      'export_error': 'Errore durante l\'esportazione',
      'swipe_hint': 'Scorri per eliminare',
      'clear_all': 'Cancella Tutto',
      'confirm_clear_all': 'Sei sicuro di voler cancellare tutte le spese?',
      'yes': 'Sì',
      'no': 'No',
      'category': 'Categoria',
      'statistics': 'Statistiche',
      'backup': 'Backup',
      'backup_export': 'Esporta Backup',
      'backup_import': 'Importa Backup',
      'backup_success': 'Backup creato con successo!',
      'backup_error': 'Errore durante il backup',
      'import_success': 'Dati importati con successo!',
      'import_error': 'Errore durante l\'importazione',
      'period': 'Periodo Budget',
      'period_monthly': 'Mensile',
      'period_weekly': 'Settimanale',
      'period_biweekly': 'Bisettimanale',
      'period_yearly': 'Annuale',
      'author': 'Autore',
      'support': 'Supporto',
      'development': 'Sviluppo',
      'version': 'Versione',
      'language_label': 'Lingua',
      'currency_label': 'Valuta',
      
      // Search & Filter
      'search_title': 'Ricerca e Filtri',
      'clear_filters_tooltip': 'Cancella filtri',
      'search_hint': 'Cerca per descrizione...',
      'category_all': 'Tutte',
      'period_button': 'Periodo',
      'expenses_found': '{count} spese trovate',
      'total_label': 'Totale: {amount}',
      'no_results': 'Nessuna spesa trovata',
      
      // Statistics
      'no_stats_data': 'Nessuna spesa da visualizzare',
      'expenses_by_category': 'Spese per Categoria',
      'category_comparison': 'Confronto Categorie',
      
      // Smart Features
      'smart_suggestions_title': '💡 Suggerimenti Smart',
      'smart_warning_title': 'Attenzione!',
      'smart_warning_msg': 'Stai spendendo il {percent}% in più del budget giornaliero',
      'smart_success_title': 'Ottimo lavoro!',
      'smart_success_msg': 'Stai risparmiando! Spesa media sotto il budget del {percent}%',
      'smart_top_cat_title': 'Categoria principale',
      'smart_top_cat_msg': '{category}: {percent}% delle spese totali',
      'smart_forecast_title': 'Previsione Budget',
      'smart_forecast_msg': 'Al ritmo attuale, supererai il budget di {amount}',
      'smart_streak_title': 'Streak di risparmio!',
      'smart_streak_msg': '{days} giorni senza spese!',
      
      // Backup Manager
      'backup_dialog_title': 'Backup e Ripristino',
      'backup_export_subtitle': 'Salva tutti i dati in un file',
      'backup_import_subtitle': 'Ripristina dati da un file',
      'backup_info': 'Il backup include: spese, budget, impostazioni e preferenze.',
      'close': 'Chiudi',
      'save_backup_dialog': 'Salva Backup',
      'select_backup_dialog': 'Seleziona Backup',
    },
    'en': {
      'title': 'Daily Budget',
      'subtitle': 'Monthly expense management',
      'target_date': 'Budget End Date',
      'total_budget': 'Available Amount',
      'hint_budget': 'Enter your total budget',
      'today': 'Today\'s Date',
      'days_remaining': 'Days Remaining',
      'daily_available': 'You can spend daily:',
      'expired': 'Expired',
      'info': 'Info',
      'add_expense': 'Add Expense',
      'expenses': 'Recent Expenses',
      'no_expenses': 'No expenses recorded',
      'spent': 'Total Spent',
      'remaining': 'Remaining',
      'description': 'Description',
      'amount': 'Amount',
      'cancel': 'Cancel',
      'add': 'Add',
      'notification_title': 'Daily Budget',
      'notification_body': 'You still have {amount} available for today!',
      'settings': 'Settings',
      'enable_notifications': 'Enable Daily Notifications',
      'export_excel': 'Export to Excel',
      'export_success': 'File exported successfully!',
      'export_error': 'Error during export',
      'swipe_hint': 'Swipe to delete',
      'clear_all': 'Clear All',
      'confirm_clear_all': 'Are you sure you want to delete all expenses?',
      'yes': 'Yes',
      'no': 'No',
      'category': 'Category',
      'statistics': 'Statistics',
      'backup': 'Backup',
      'backup_export': 'Export Backup',
      'backup_import': 'Import Backup',
      'backup_success': 'Backup created successfully!',
      'backup_error': 'Error during backup',
      'import_success': 'Data imported successfully!',
      'import_error': 'Error during import',
      'period': 'Budget Period',
      'period_monthly': 'Monthly',
      'period_weekly': 'Weekly',
      'period_biweekly': 'Bi-weekly',
      'period_yearly': 'Yearly',
      'author': 'Author',
      'support': 'Support',
      'development': 'Development',
      'version': 'Version',
      'language_label': 'Language',
      'currency_label': 'Currency',
      
      // Search & Filter
      'search_title': 'Search & Filters',
      'clear_filters_tooltip': 'Clear filters',
      'search_hint': 'Search by description...',
      'category_all': 'All',
      'period_button': 'Period',
      'expenses_found': '{count} expenses found',
      'total_label': 'Total: {amount}',
      'no_results': 'No expenses found',
      
      // Statistics
      'no_stats_data': 'No expenses to display',
      'expenses_by_category': 'Expenses by Category',
      'category_comparison': 'Category Comparison',
      
      // Smart Features
      'smart_suggestions_title': '💡 Smart Suggestions',
      'smart_warning_title': 'Warning!',
      'smart_warning_msg': 'You are spending {percent}% more than daily budget',
      'smart_success_title': 'Great job!',
      'smart_success_msg': 'You are saving! Average spending below budget by {percent}%',
      'smart_top_cat_title': 'Top Category',
      'smart_top_cat_msg': '{category}: {percent}% of total expenses',
      'smart_forecast_title': 'Budget Forecast',
      'smart_forecast_msg': 'At current rate, you will exceed budget by {amount}',
      'smart_streak_title': 'Saving Streak!',
      'smart_streak_msg': '{days} days without expenses!',
      
      // Backup Manager
      'backup_dialog_title': 'Backup & Restore',
      'backup_export_subtitle': 'Save all data to a file',
      'backup_import_subtitle': 'Restore data from a file',
      'backup_info': 'Backup includes: expenses, budget, settings and preferences.',
      'close': 'Close',
      'save_backup_dialog': 'Save Backup',
      'select_backup_dialog': 'Select Backup',
    },
    'es': {
      'title': 'Presupuesto Diario',
      'subtitle': 'Gestión de gastos mensuales',
      'target_date': 'Fecha Fin Presupuesto',
      'total_budget': 'Monto Disponible',
      'hint_budget': 'Introduce tu presupuesto total',
      'today': 'Fecha de Hoy',
      'days_remaining': 'Días Restantes',
      'daily_available': 'Puedes gastar al día:',
      'expired': 'Caducado',
      'info': 'Información',
      'add_expense': 'Añadir Gasto',
      'expenses': 'Gastos Recientes',
      'no_expenses': 'No hay gastos registrados',
      'spent': 'Total Gastado',
      'remaining': 'Restante',
      'description': 'Descripción',
      'amount': 'Monto',
      'cancel': 'Cancelar',
      'add': 'Añadir',
      'notification_title': 'Presupuesto Diario',
      'notification_body': '¡Todavía tienes {amount} disponibles para hoy!',
      'settings': 'Ajustes',
      'enable_notifications': 'Activar Notificaciones Diarias',
      'export_excel': 'Exportar a Excel',
      'export_success': '¡Archivo exportado con éxito!',
      'export_error': 'Error durante la exportación',
      'swipe_hint': 'Desliza para eliminar',
      'clear_all': 'Borrar Todo',
      'confirm_clear_all': '¿Estás seguro de que quieres borrar todos los gastos?',
      'yes': 'Sí',
      'no': 'No',
      'category': 'Categoría',
      'statistics': 'Estadísticas',
      'backup': 'Copia de Seguridad',
      'backup_export': 'Exportar Copia',
      'backup_import': 'Importar Copia',
      'backup_success': '¡Copia creada con éxito!',
      'backup_error': 'Error durante la copia',
      'import_success': '¡Datos importados con éxito!',
      'import_error': 'Error durante la importación',
      'period': 'Período Presupuesto',
      'period_monthly': 'Mensual',
      'period_weekly': 'Semanal',
      'period_biweekly': 'Quincenal',
      'period_yearly': 'Anual',
      'author': 'Autor',
      'support': 'Soporte',
      'development': 'Desarrollo',
      'version': 'Versión',
      'language_label': 'Idioma',
      'currency_label': 'Moneda',
      
      // Search & Filter
      'search_title': 'Búsqueda y Filtros',
      'clear_filters_tooltip': 'Borrar filtros',
      'search_hint': 'Buscar por descripción...',
      'category_all': 'Todas',
      'period_button': 'Período',
      'expenses_found': '{count} gastos encontrados',
      'total_label': 'Total: {amount}',
      'no_results': 'No se encontraron gastos',
      
      // Statistics
      'no_stats_data': 'No hay gastos para mostrar',
      'expenses_by_category': 'Gastos por Categoría',
      'category_comparison': 'Comparación de Categorías',
      
      // Smart Features
      'smart_suggestions_title': '💡 Sugerencias Inteligentes',
      'smart_warning_title': '¡Atención!',
      'smart_warning_msg': 'Estás gastando un {percent}% más que el presupuesto diario',
      'smart_success_title': '¡Buen trabajo!',
      'smart_success_msg': '¡Estás ahorrando! Gasto promedio por debajo del presupuesto en un {percent}%',
      'smart_top_cat_title': 'Categoría Principal',
      'smart_top_cat_msg': '{category}: {percent}% del total de gastos',
      'smart_forecast_title': 'Previsión de Presupuesto',
      'smart_forecast_msg': 'Al ritmo actual, superarás el presupuesto en {amount}',
      'smart_streak_title': '¡Racha de Ahorro!',
      'smart_streak_msg': '¡{days} días sin gastos!',
      
      // Backup Manager
      'backup_dialog_title': 'Copia de Seguridad y Restauración',
      'backup_export_subtitle': 'Guardar todos los datos en un archivo',
      'backup_import_subtitle': 'Restaurar datos desde un archivo',
      'backup_info': 'La copia incluye: gastos, presupuesto, ajustes y preferencias.',
      'close': 'Cerrar',
      'save_backup_dialog': 'Guardar Copia',
      'select_backup_dialog': 'Seleccionar Copia',
    },
    'fr': {
      'title': 'Budget Quotidien',
      'subtitle': 'Gestion des dépenses mensuelles',
      'target_date': 'Date Fin Budget',
      'total_budget': 'Montant Disponible',
      'hint_budget': 'Entrez votre budget total',
      'today': 'Date d\'Aujourd\'hui',
      'days_remaining': 'Jours Restants',
      'daily_available': 'Vous pouvez dépenser par jour :',
      'expired': 'Expiré',
      'info': 'Infos',
      'add_expense': 'Ajouter Dépense',
      'expenses': 'Dépenses Récentes',
      'no_expenses': 'Aucune dépense enregistrée',
      'spent': 'Total Dépensé',
      'remaining': 'Restant',
      'description': 'Description',
      'amount': 'Montant',
      'cancel': 'Annuler',
      'add': 'Ajouter',
      'notification_title': 'Budget Quotidien',
      'notification_body': 'Vous avez encore {amount} disponibles pour aujourd\'hui !',
      'settings': 'Paramètres',
      'enable_notifications': 'Activer Notifications Quotidiennes',
      'export_excel': 'Exporter vers Excel',
      'export_success': 'Fichier exporté avec succès !',
      'export_error': 'Erreur lors de l\'exportation',
      'swipe_hint': 'Glisser pour supprimer',
      'clear_all': 'Tout Effacer',
      'confirm_clear_all': 'Êtes-vous sûr de vouloir supprimer toutes les dépenses ?',
      'yes': 'Oui',
      'no': 'Non',
      'category': 'Catégorie',
      'statistics': 'Statistiques',
      'backup': 'Sauvegarde',
      'backup_export': 'Exporter Sauvegarde',
      'backup_import': 'Importer Sauvegarde',
      'backup_success': 'Sauvegarde créée avec succès !',
      'backup_error': 'Erreur lors de la sauvegarde',
      'import_success': 'Données importées avec succès !',
      'import_error': 'Erreur lors de l\'importation',
      'period': 'Période Budget',
      'period_monthly': 'Mensuel',
      'period_weekly': 'Hebdomadaire',
      'period_biweekly': 'Bihebdomadaire',
      'period_yearly': 'Annuel',
      'author': 'Auteur',
      'support': 'Support',
      'development': 'Développement',
      'version': 'Version',
      'language_label': 'Langue',
      'currency_label': 'Devise',
      
      // Search & Filter
      'search_title': 'Recherche et Filtres',
      'clear_filters_tooltip': 'Effacer les filtres',
      'search_hint': 'Rechercher par description...',
      'category_all': 'Toutes',
      'period_button': 'Période',
      'expenses_found': '{count} dépenses trouvées',
      'total_label': 'Total : {amount}',
      'no_results': 'Aucune dépense trouvée',
      
      // Statistics
      'no_stats_data': 'Aucune dépense à afficher',
      'expenses_by_category': 'Dépenses par Catégorie',
      'category_comparison': 'Comparaison des Catégories',
      
      // Smart Features
      'smart_suggestions_title': '💡 Suggestions Intelligentes',
      'smart_warning_title': 'Attention !',
      'smart_warning_msg': 'Vous dépensez {percent}% de plus que le budget quotidien',
      'smart_success_title': 'Beau travail !',
      'smart_success_msg': 'Vous économisez ! Dépenses moyennes inférieures au budget de {percent}%',
      'smart_top_cat_title': 'Catégorie Principale',
      'smart_top_cat_msg': '{category} : {percent}% des dépenses totales',
      'smart_forecast_title': 'Prévision Budgétaire',
      'smart_forecast_msg': 'Au rythme actuel, vous dépasserez le budget de {amount}',
      'smart_streak_title': 'Série d\'Économie !',
      'smart_streak_msg': '{days} jours sans dépenses !',
      
      // Backup Manager
      'backup_dialog_title': 'Sauvegarde et Restauration',
      'backup_export_subtitle': 'Enregistrer toutes les données dans un fichier',
      'backup_import_subtitle': 'Restaurer les données à partir d\'un fichier',
      'backup_info': 'La sauvegarde inclut : dépenses, budget, paramètres et préférences.',
      'close': 'Fermer',
      'save_backup_dialog': 'Enregistrer Sauvegarde',
      'select_backup_dialog': 'Sélectionner Sauvegarde',
    },
    'de': {
      'title': 'Tagesbudget',
      'subtitle': 'Monatliche Ausgabenverwaltung',
      'target_date': 'Budget-Enddatum',
      'total_budget': 'Verfügbarer Betrag',
      'hint_budget': 'Geben Sie Ihr Gesamtbudget ein',
      'today': 'Heutiges Datum',
      'days_remaining': 'Verbleibende Tage',
      'daily_available': 'Sie können täglich ausgeben:',
      'expired': 'Abgelaufen',
      'info': 'Info',
      'add_expense': 'Ausgabe Hinzufügen',
      'expenses': 'Letzte Ausgaben',
      'no_expenses': 'Keine Ausgaben erfasst',
      'spent': 'Gesamt Ausgegeben',
      'remaining': 'Verbleibend',
      'description': 'Beschreibung',
      'amount': 'Betrag',
      'cancel': 'Abbrechen',
      'add': 'Hinzufügen',
      'notification_title': 'Tagesbudget',
      'notification_body': 'Sie haben noch {amount} für heute verfügbar!',
      'settings': 'Einstellungen',
      'enable_notifications': 'Tägliche Benachrichtigungen aktivieren',
      'export_excel': 'Nach Excel exportieren',
      'export_success': 'Datei erfolgreich exportiert!',
      'export_error': 'Fehler beim Exportieren',
      'swipe_hint': 'Zum Löschen wischen',
      'clear_all': 'Alles Löschen',
      'confirm_clear_all': 'Sind Sie sicher, dass Sie alle Ausgaben löschen möchten?',
      'yes': 'Ja',
      'no': 'Nein',
      'category': 'Kategorie',
      'statistics': 'Statistiken',
      'backup': 'Sicherung',
      'backup_export': 'Sicherung Exportieren',
      'backup_import': 'Sicherung Importieren',
      'backup_success': 'Sicherung erfolgreich erstellt!',
      'backup_error': 'Fehler bei der Sicherung',
      'import_success': 'Daten erfolgreich importiert!',
      'import_error': 'Fehler beim Importieren',
      'period': 'Budgetzeitraum',
      'period_monthly': 'Monatlich',
      'period_weekly': 'Wöchentlich',
      'period_biweekly': 'Zweiwöchentlich',
      'period_yearly': 'Jährlich',
      'author': 'Autor',
      'support': 'Unterstützung',
      'development': 'Entwicklung',
      'version': 'Version',
      'language_label': 'Sprache',
      'currency_label': 'Währung',
      
      // Search & Filter
      'search_title': 'Suche und Filter',
      'clear_filters_tooltip': 'Filter löschen',
      'search_hint': 'Nach Beschreibung suchen...',
      'category_all': 'Alle',
      'period_button': 'Zeitraum',
      'expenses_found': '{count} Ausgaben gefunden',
      'total_label': 'Gesamt: {amount}',
      'no_results': 'Keine Ausgaben gefunden',
      
      // Statistics
      'no_stats_data': 'Keine Ausgaben zum Anzeigen',
      'expenses_by_category': 'Ausgaben nach Kategorie',
      'category_comparison': 'Kategorienvergleich',
      
      // Smart Features
      'smart_suggestions_title': '💡 Intelligente Vorschläge',
      'smart_warning_title': 'Achtung!',
      'smart_warning_msg': 'Sie geben {percent}% mehr aus als das Tagesbudget',
      'smart_success_title': 'Gut gemacht!',
      'smart_success_msg': 'Sie sparen! Durchschnittliche Ausgaben {percent}% unter dem Budget',
      'smart_top_cat_title': 'Top-Kategorie',
      'smart_top_cat_msg': '{category}: {percent}% der Gesamtausgaben',
      'smart_forecast_title': 'Budgetprognose',
      'smart_forecast_msg': 'Bei aktuellem Tempo werden Sie das Budget um {amount} überschreiten',
      'smart_streak_title': 'Sparsträhne!',
      'smart_streak_msg': '{days} Tage ohne Ausgaben!',
      
      // Backup Manager
      'backup_dialog_title': 'Sicherung und Wiederherstellung',
      'backup_export_subtitle': 'Alle Daten in einer Datei speichern',
      'backup_import_subtitle': 'Daten aus einer Datei wiederherstellen',
      'backup_info': 'Die Sicherung umfasst: Ausgaben, Budget, Einstellungen und Präferenzen.',
      'close': 'Schließen',
      'save_backup_dialog': 'Sicherung speichern',
      'select_backup_dialog': 'Sicherung auswählen',
    },
  };

  static String get(BuildContext context, String key, {String? languageCode}) {
    final locale = languageCode ?? Localizations.localeOf(context).languageCode;
    return _localizedValues[locale]?[key] ?? _localizedValues['it']![key] ?? key;
  }
  
  // Helper for non-context usage if needed, though context is preferred for locale
  static String getSimple(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? _localizedValues['it']![key] ?? key;
  }
}
